src/com/cdel/advc/innermsg/domain/InnerMsg.java
package com.cdel.advc.innermsg.domain;

import java.util.Date;

import org.apache.commons.lang.StringUtils;

import com.cdel.util.Contants;
import com.cdel.util.DateUtil;

/**
 * 
 * <p>班级内部沟通消息 实体</p>
 * 
 * @author Du Haiying
 * Create at:2013-7-26 下午4:11:22
 */
@SuppressWarnings("serial")
public class InnerMsg extends InnerMsgReceive implements java.io.Serializable {

	/** ID */
	private Integer innerMsgID;
	
	/** 班级ID */
	private Integer referClass;
	
	/** 学员ID(接收人) */
	private String referUser;// 
	
	/** 发送人 */
	private Integer sender;
	
	/** 发送时间 */
	private Date sendTime;
	
	/** 发送内容   */
	private String innerMsgContent;
	
	/** 状态  */
	private Short status;
	
	// ------------------------------------------------
	
	/** 内部消息接受人 教师ID 字符串（多个以逗号相隔） */
	private  String receiveTeacherIDStr;
	
	private String className;// 相关班级
	
	private Short mailType;// 邮件类型
	
	private String replyContent;// 回复内容
	
	public String getReceiveTeacherIDStr() {
		return receiveTeacherIDStr;
	}

	public void setReceiveTeacherIDStr(String receiveTeacherIDStr) {
		this.receiveTeacherIDStr = receiveTeacherIDStr;
	}

	public Integer getInnerMsgID() {
		return innerMsgID;
	}

	public void setInnerMsgID(Integer innerMsgID) {
		this.innerMsgID = innerMsgID;
	}

	public Integer getReferClass() {
		return referClass;
	}

	public void setReferClass(Integer referClass) {
		this.referClass = referClass;
	}

	public String getReferUser() {
		return referUser;
	}

	public void setReferUser(String referUser) {
		this.referUser = referUser;
	}

	public Integer getSender() {
		return sender;
	}

	public void setSender(Integer sender) {
		this.sender = sender;
	}

	public Date getSendTime() {
		return sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public String getSendTimeStr() {
		return DateUtil.getNowDateString(sendTime, "yyyy-MM-dd HH:mm");
	}

	public String getInnerMsgContent() {
		return innerMsgContent;
	}

	public void setInnerMsgContent(String innerMsgContent) {
		this.innerMsgContent = innerMsgContent;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public String getStatusStr() {
		if (status == null) {
			return "";
		} else {
			return Contants.status.get(status);
		}
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public Short getMailType() {
		return mailType;
	}

	public void setMailType(Short mailType) {
		this.mailType = mailType;
	}

	public String getAskContent() {
		if (innerMsgContent == null) {
			return "";
		} else if (StringUtils.indexOf(innerMsgContent, "<br>") > -1) {
			return StringUtils.substring(innerMsgContent, 0,
					StringUtils.indexOf(innerMsgContent, "<br>"));
		} else {
			return innerMsgContent;
		}
	}

	public String getAskContentPart() {
		String askContent = getAskContent();
		if (askContent != null) {
			if (StringUtils.substring(askContent, 0, 20).equals(askContent)) {
				return askContent;
			} else {
				return StringUtils.substring(askContent, 0, 20) + "...";
			}
		} else {
			return "";
		}
	}

	public String getInnerMsgContentStr() {
		if (innerMsgContent == null) {
			return "";
		}
		if (StringUtils.indexOf(innerMsgContent, "<br>") == -1) {
			return "无";
		}
		String str = StringUtils.substring(innerMsgContent,
				StringUtils.indexOf(innerMsgContent, "<br>"));
		// 重新排序
		String[] arr = StringUtils.splitByWholeSeparator(str, "<br>");
		String[] arrnew = new String[arr.length];
		for (int i = 0; i < arr.length; i++) {
			arrnew[i] = arr[arr.length - 1 - i];
		}
		return StringUtils.join(arrnew, "<br>");
	}

	public String getInnerMsgContentStrPart() {
		String str = getInnerMsgContentStr();
		if (StringUtils.indexOf(str, "</font>)<br>") > -1) {
			return StringUtils.substring(str, 0,
					StringUtils.indexOf(str, "</font>)<br>") + 8)
					+ "...";
		} else {
			return str;
		}
	}

	public String getReplyContent() {
		return replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

}

src/com/cdel/advc/innermsg/domain/InnerMsgAll.java
package com.cdel.advc.innermsg.domain;

@SuppressWarnings("serial")
public class InnerMsgAll extends InnerMsg implements java.io.Serializable {
	private Integer orgID;// 教师所在机构

	public Integer getOrgID() {
		return orgID;
	}

	public void setOrgID(Integer orgID) {
		this.orgID = orgID;
	}

}

src/com/cdel/advc/innermsg/domain/InnerMsgReceive.java
package com.cdel.advc.innermsg.domain;

import java.util.Date;
import com.cdel.util.Contants;
import com.cdel.util.DateUtil;
import com.chnedu.plat.rad.domain.BaseDomain;

@SuppressWarnings("serial")
public class InnerMsgReceive extends BaseDomain implements java.io.Serializable {

	private Integer receiveID;
	private Integer innerMsgID;
	private Date readTime;// 阅读时间
	private Short readStatus;// 阅读状态
	private Integer receiveTeacherID;// 接收老师ID
	private String senderName;// 发送人姓名
	private String receiveName;// 接收人姓名
	private String teacherCode;// 接收/发送人代码
	private String receiverName;// 接收人串

	public Integer getInnerMsgID() {
		return innerMsgID;
	}

	public void setInnerMsgID(Integer innerMsgID) {
		this.innerMsgID = innerMsgID;
	}

	public Date getReadTime() {
		return readTime;
	}

	public void setReadTime(Date readTime) {
		this.readTime = readTime;
	}

	public String getReadTimeStr() {
		return DateUtil.getNowDateString(readTime, "yyyy-MM-dd HH:mm");
	}

	public Short getReadStatus() {
		return readStatus;
	}

	public void setReadStatus(Short readStatus) {
		this.readStatus = readStatus;
	}

	public String getReadStatusStr() {
		if (readStatus == null) {
			return "--";
		} else {
			return Contants.readStatus.get(readStatus);
		}
	}

	public Integer getReceiveTeacherID() {
		return receiveTeacherID;
	}

	public void setReceiveTeacherID(Integer receiveTeacherID) {
		this.receiveTeacherID = receiveTeacherID;
	}

	public Integer getReceiveID() {
		return receiveID;
	}

	public void setReceiveID(Integer receiveID) {
		this.receiveID = receiveID;
	}

	public String getSenderName() {
		return senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	public String getTeacherCode() {
		return teacherCode;
	}

	public void setTeacherCode(String teacherCode) {
		this.teacherCode = teacherCode;
	}

	public String getReceiverName() {
		return receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	public String getReceiveName() {
		return receiveName;
	}

	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

}

src/com/cdel/advc/innermsg/action/InnerMsgAction.java
package com.cdel.advc.innermsg.action;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import org.primefaces.model.LazyDataModel;

import com.cdel.advc.innermsg.domain.InnerMsg;
import com.cdel.advc.innermsg.facade.InnerMsgFacade;
import com.cdel.util.BaseAction;

@SuppressWarnings("serial")
@ManagedBean
@ViewScoped
public class InnerMsgAction extends BaseAction<InnerMsg> implements
		Serializable {
	@ManagedProperty(value = "#{innerMsgFacade}")
	private InnerMsgFacade innerMsgFacade;

	private LazyDataModel<InnerMsg> innerMsgPage;
	private InnerMsg searchInnerMsg = new InnerMsg();
	private List<InnerMsg> innerMsgList;
	private Integer siteID;// 网站ID
	private boolean showMark = true;// 是否显示标记按钮
	private boolean showBtn = true;// 是否可以提交回复

	@PostConstruct
	public void initInnerMsgAction() {
		Integer loginID = this.getCurrentUserID();
		siteID = this.getCurrentSiteID();
		if (loginID != null) {
			searchInnerMsg.setReceiveTeacherID(loginID);
			searchInnerMsg.setSender(loginID);
		}
		Integer flag = this.getIntegerParameter("flag");
		// 我的沟通消息页面，可以从班级管理中的沟通消息进入。从班级管理中进入我的沟通消息，需要flag区分收信箱：1、 发信箱：2
		if (flag != null && (flag == 1 || flag == 2)) {
			super.heighti2 = super.calHeight(14.6f / 20);
		} else {
			super.heighti2 = super.calHeight(12f / 20);
		}
		if (flag == null) {
			flag = 1;
		}
		if (flag == 1) {
			searchInnerMsg.setMailType((short) 1);
		} else if (flag == 2) {
			showBtn = false;
			searchInnerMsg.setMailType((short) 2);
		}
		searchInnerMsg.setReadStatus((short) 0);
		this.innerMsgPage = this.innerMsgFacade.findPage(searchInnerMsg);
	}

	/**
	 * 查询
	 * 
	 * @throws Exception
	 */
	public void search() {
		if (searchInnerMsg.getMailType() == null
				|| searchInnerMsg.getMailType() == 2) {
			showMark = false;
			showBtn = false;
		} else {
			showMark = true;
			showBtn = true;
		}
		pageTable.setFirst(0);
		search4U();
	}

	/**
	 * 查询
	 * 
	 * @throws Exception
	 */
	public void search4U() {
		this.innerMsgPage = this.innerMsgFacade.findPage(searchInnerMsg);
		this.updateComponent("searchForm:innerMsgList");
		this.updateComponent("searchForm:showMarkBtn");
	}

	public void setInnerMsgFacade(InnerMsgFacade innerMsgFacade) {
		this.innerMsgFacade = innerMsgFacade;
	}

	public InnerMsg getSearchInnerMsg() {
		return searchInnerMsg;
	}

	public void setSearchInnerMsg(InnerMsg searchInnerMsg) {
		this.searchInnerMsg = searchInnerMsg;
	}

	public LazyDataModel<InnerMsg> getInnerMsgPage() {
		return innerMsgPage;
	}

	public void setInnerMsgPage(LazyDataModel<InnerMsg> innerMsgPage) {
		this.innerMsgPage = innerMsgPage;
	}

	public List<InnerMsg> getInnerMsgList() {
		return innerMsgList;
	}

	public void setInnerMsgList(List<InnerMsg> innerMsgList) {
		this.innerMsgList = innerMsgList;
	}

	public boolean isShowMark() {
		return showMark;
	}

	public void setShowMark(boolean showMark) {
		this.showMark = showMark;
	}

	public Integer getSiteID() {
		return siteID;
	}

	public boolean isShowBtn() {
		return showBtn;
	}

}

src/com/cdel/advc/innermsg/action/InnerMsgAllAction.java
package com.cdel.advc.innermsg.action;

import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.primefaces.model.LazyDataModel;
import com.cdel.advc.innermsg.domain.InnerMsgAll;
import com.cdel.advc.innermsg.facade.InnerMsgAllFacade;
import com.cdel.advc.teacher.domain.Teacher;
import com.cdel.util.BaseAction;

@SuppressWarnings("serial")
@ManagedBean
@ViewScoped
public class InnerMsgAllAction extends BaseAction<InnerMsgAll> implements
		Serializable {
	@ManagedProperty(value = "#{innerMsgAllFacade}")
	private InnerMsgAllFacade innerMsgAllFacade;

	private LazyDataModel<InnerMsgAll> innerMsgPage;
	private InnerMsgAll searchInnerMsg = new InnerMsgAll();
	private List<InnerMsgAll> innerMsgList;
	private Integer siteID;// 网站ID

	@PostConstruct
	public void initInnerMsgAction() {
		siteID = this.getCurrentSiteID();
		Teacher teacher = this.getCurrentTeacher();
		Integer orgID = teacher.getOrgID();
		Short isHeader = teacher.getIsHeader();
		if (isHeader == 0) {// 超管
			searchInnerMsg.setOrgID(null);
		} else if (isHeader == 1 || isHeader == 4) {// 经理
			searchInnerMsg.setOrgID(null);
		} else if (isHeader == 2) {// 组长
			searchInnerMsg.setOrgID(orgID);
		}
		this.innerMsgPage = this.innerMsgAllFacade.findPage(searchInnerMsg);
	}

	/**
	 * 查询
	 * 
	 * @throws Exception
	 */
	public void search() {
		pageTable.setFirst(0);
		this.innerMsgPage = this.innerMsgAllFacade.findPage(searchInnerMsg);
		this.updateComponent("searchForm:innerMsgList");
	}

	public LazyDataModel<InnerMsgAll> getInnerMsgPage() {
		return innerMsgPage;
	}

	public void setInnerMsgPage(LazyDataModel<InnerMsgAll> innerMsgPage) {
		this.innerMsgPage = innerMsgPage;
	}

	public InnerMsgAll getSearchInnerMsg() {
		return searchInnerMsg;
	}

	public void setSearchInnerMsg(InnerMsgAll searchInnerMsg) {
		this.searchInnerMsg = searchInnerMsg;
	}

	public List<InnerMsgAll> getInnerMsgList() {
		return innerMsgList;
	}

	public void setInnerMsgList(List<InnerMsgAll> innerMsgList) {
		this.innerMsgList = innerMsgList;
	}

	public void setInnerMsgAllFacade(InnerMsgAllFacade innerMsgAllFacade) {
		this.innerMsgAllFacade = innerMsgAllFacade;
	}

	public Integer getSiteID() {
		return siteID;
	}

}

WebRoot/page/innermsg/innermsgList.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>我的沟通消息</title>
	<h:outputStylesheet name="page-css.css" library="css"/>
	<h:outputScript name="page.js" library="js"/>
	<script>
	function setValue(referUser){
		jQuery("#searchForm\\:sReferUser").val(referUser);
		jQuery("#searchForm\\:sReadStatus_input").val("0");
		jQuery("#searchForm\\:sReadStatus_label").text("未读");
	}
	</script>
</h:head>
<h:body>
	<p:growl for="info" id="info" life="3000" />
	<h:form id="searchForm" >
	<p:panel id="dataTablePanel">
		<p:fieldset legend="查询条件" toggleable="true" collapsed="true" widgetVar="searchFieldSet">
		<p:panelGrid columns="4" style="width:100%; text-align:left;">
			<h:outputLabel for="sReferUser" value="相关学员" />
			<p:inputText id="sReferUser" value="#{innerMsgAction.searchInnerMsg.referUser}" styleClass="minLength"/>
			
			<h:outputLabel for="sMailType" value="我的邮箱 "/>
			<p:selectOneMenu id="sMailType" value="#{innerMsgAction.searchInnerMsg.mailType}" style="width:200px;" panelStyleClass="minLength">
				<f:selectItem itemLabel="--请选择--" itemValue="" />
				<f:selectItems value="#{innerMsgReqAction.mailType.entrySet()}" var="mailType" itemLabel="#{mailType.value}" itemValue="#{mailType.key}"/>
			</p:selectOneMenu>
			
			<h:outputLabel for="sReadStatus" value="阅读状态" />
			<p:selectOneMenu id="sReadStatus" value="#{innerMsgAction.searchInnerMsg.readStatus}" style="width:200px;" panelStyleClass="minLength">
				<f:selectItem itemLabel="--请选择--" itemValue="" />
				<f:selectItems value="#{innerMsgReqAction.readStatus.entrySet()}" var="readStatus" itemLabel="#{readStatus.value}" itemValue="#{readStatus.key}"/>
			</p:selectOneMenu>
			
			<p:outputLabel/>
			<p:outputLabel/>
			
			<f:facet name="footer">
				<h:panelGroup style="display:block; text-align:center">
					<p:commandButton id="searchBtn" value="查询" oncomplete="searchFieldSet.toggle();" actionListener="#{innerMsgAction.search}" rendered="#{innerMsgAction.viewAuth}" />
					<p:spacer width="10px"/>
					<p:commandButton type="reset" value="重置" />
				</h:panelGroup>
			</f:facet>	
		</p:panelGrid>
		</p:fieldset>
		<p:menubar id="showMarkBtn" >
			<p:menuitem value="标记为已读" icon="ui-icon-pencil" 
				actionListener="#{innerMsgReqAction.markRead}" rendered="#{innerMsgAction.optAuth and innerMsgAction.searchInnerMsg.readStatus==0}" update=":info" />
			<p:menuitem value="转到答疑板站内信" icon="ui-icon-gear" target="_blank" url="#{innerMsgReqAction.faqurl}&amp;userName=#{innerMsgReqAction.userName}&amp;secret=#{innerMsgReqAction.secret}" />
		</p:menubar>
		<p:dataTable scrollable="true" scrollHeight="#{innerMsgAction.heighti2}" 
			widgetVar="innerMsg"
			id="innerMsgList"
			binding="#{innerMsgAction.pageTable}"
			lazy="true"
			value="#{innerMsgAction.innerMsgPage}" 
			rows="20"
			var="innerMsg" 
			paginator="true" 
			paginatorPosition="bottom"
			currentPageReportTemplate="{currentPage} of {totalPages}  共 {totalRecords}条记录"
			paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowIndexVar="row"
			rowsPerPageTemplate="20,50"
			styleClass="gridTable" 
			selection="#{innerMsgReqAction.selectInnerMsg}"
			rowKey="#{innerMsg.innerMsgID}"
			emptyMessage="对不起，没有查询到数据！"
			>
			<p:column width="5%" selectionMode="multiple" rendered="#{innerMsgAction.showMark}"/>
			<p:column headerText="详情" width="5%">
				<p:rowToggler />
			</p:column>
			<p:rowExpansion>
			<p:panelGrid columns="2" style="width:40%; text-align:left;" columnClasses="addObjectClass, addContentClass">
				<h:outputText value="操作" />
				<h:panelGroup style="display:block;">
					<p:commandLink value="查看" actionListener="#{innerMsgReqAction.getRecerveDetail(innerMsg.innerMsgID,innerMsg.receiveID,0)}" 
						oncomplete="detailDialog.show();" update=":detailForm:detailDialog" rendered="#{innerMsgReqAction.viewAuth}"/>
					<p:spacer width="5px"/>
					<p:commandLink value="查看接收人" actionListener="#{innerMsgReqAction.getRecerveList(innerMsg.innerMsgID,0)}" 
						oncomplete="loadDialog.show()" update=":loadForm:loadDialog" rendered="#{innerMsgReqAction.viewAuth}"/>
				</h:panelGroup>
				<h:outputText value="原问题" />
				<h:outputText value="#{innerMsg.askContent}" escape="false" />
				<h:outputText value="回复内容" />
				<h:outputText value="#{innerMsg.innerMsgContentStr}" escape="false" />
			</p:panelGrid>
			</p:rowExpansion>
			<p:column headerText="发送人" width="15%">
				<h:outputText value="#{innerMsg.teacherCode}(#{innerMsg.senderName})"/>
			</p:column>
			<p:column headerText="相关班级" width="15%">
				<h:link value="#{innerMsg.className}" title="#{innerMsg.className}" 
					outcome="/page/memberClass/memberClassList" includeViewParams="true" target="_blank">
					<f:param name="classID" value="#{innerMsg.referClass}"/>
					<f:param name="siteID" value="#{innerMsgAction.siteID}"/>
				</h:link>
			</p:column>
			<p:column headerText="原问题" width="18%">
				<h:outputText value="#{innerMsg.askContentPart}" escape="false" title="#{innerMsg.askContent}"/>
			</p:column>
			<p:column headerText="回复内容" width="18%">
				<h:outputText value="#{innerMsg.innerMsgContentStrPart}" escape="false" />
			</p:column>
			<p:column headerText="阅读" width="7%">
				<h:outputText value="#{innerMsg.readStatusStr}"/>
			</p:column>
			<p:column headerText="相关学员" width="10%">
				<p:commandLink value="#{innerMsg.referUser}" onclick="setValue('#{innerMsg.referUser}')" actionListener="#{innerMsgAction.search}" title="点击查看有关此学员的未读消息" rendered="#{innerMsgAction.viewAuth}"/>
			</p:column>
			<p:column headerText="状态" width="7%" style="text-align:center">
				<p:commandLink value="#{innerMsg.statusStr}" update=":searchForm:innerMsgList :info" actionListener="#{innerMsgReqAction.changeStatus(innerMsg.innerMsgID,innerMsg.status)}" styleClass="status-#{innerMsg.status}" rendered="#{innerMsgReqAction.optAuth}"/>
				<h:outputText value="#{innerMsg.statusStr}" rendered="#{!innerMsgReqAction.optAuth}"/>
			</p:column>
		</p:dataTable>
		<ui:include src="/page/common/blockUI.xhtml">
			<ui:param name="tableID" value="innerMsgList" />
		</ui:include>
	</p:panel>
	</h:form>
	
	<!-- 查看页面 -->
	<h:form id="loadForm" >
		<p:dialog id="loadDialog" header="接收人" widgetVar="loadDialog" resizable="false" showEffect="fade" hideEffect="fade">
			<ui:include src="load/innermsgShow.xhtml"/>
		</p:dialog>
	</h:form>
	<!-- 明细页面 -->
	<h:form id="detailForm" >
		<p:dialog id="detailDialog" widgetVar="detailDialog" resizable="false" showEffect="fade" hideEffect="fade">
			<ui:include src="load/innermsgDetail.xhtml"/>
		</p:dialog>
	</h:form>
</h:body>
</html>