src/com/cdel/advc/major/domain/ClassNo.java
package com.cdel.advc.major.domain;

import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * 辅导的当前班级数
 * 
 * @author zhangsulei
 */

public class ClassNo extends BaseDomain implements java.io.Serializable {
	private static final long serialVersionUID = 7193900830270819888L;

	private Integer majorID;
	private Short classType;// 类型1:实验,2:精品,3:混合
	private Short currClassNo;// 当前的班级数
	private String classTypeName;// 类型1:实验,2:精品,3:混合

	public Integer getMajorID() {
		return majorID;
	}

	public void setMajorID(Integer majorID) {
		this.majorID = majorID;
	}

	public Short getClassType() {
		return classType;
	}

	public void setClassType(Short classType) {
		this.classType = classType;
	}

	public Short getCurrClassNo() {
		return currClassNo;
	}

	public void setCurrClassNo(Short currClassNo) {
		this.currClassNo = currClassNo;
	}

	public String getClassTypeName() {
		return classTypeName;
	}

	public void setClassTypeName(String classTypeName) {
		this.classTypeName = classTypeName;
	}

}

src/com/cdel/advc/major/domain/GuideLanguage.java
package com.cdel.advc.major.domain;

import java.util.Date;
import com.cdel.util.Contants;
import com.cdel.util.DateUtil;

/**
 * GuideLanguage entity.
 * 
 * @author xxg
 */
@SuppressWarnings("serial")
public class GuideLanguage extends PromptTime implements java.io.Serializable {

	private Integer guideLanguageID;// 自增长主主键
	private Integer majorID; // 辅导id
	private Integer stageID; // 阶段id
	private Integer serviceID; // 服务项id
	private Short promptKey; // 提示时间
	private String promptContent;// 提示内容
	private Short status;// 是否有效
	private Date createTime;// 创建时间
	private Integer createID;// 创建人id

	// -------------------------------------------------------------------------------------

	private String stageName;// 阶段名称
	private String serviceName;// 服务项名称

	public String getStatusStr() {
		if (status == null) {
			return "";
		} else {
			return Contants.status.get(status);
		}
	}

	public String getCreateTimeStr() {
		return DateUtil.getNowDateString(createTime, "yyyy-MM-dd");
	}

	public Integer getMajorID() {
		return majorID;
	}

	public void setMajorID(Integer majorID) {
		this.majorID = majorID;
	}

	public Integer getStageID() {
		return stageID;
	}

	public void setStageID(Integer stageID) {
		this.stageID = stageID;
	}

	public String getStageName() {
		return stageName;
	}

	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

	public Integer getServiceID() {
		return serviceID;
	}

	public void setServiceID(Integer serviceID) {
		this.serviceID = serviceID;
	}

	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public Short getPromptKey() {
		return promptKey;
	}

	public void setPromptKey(Short promptKey) {
		this.promptKey = promptKey;
	}

	public String getPromptName() {
		if (promptKey != null) {
			return Contants.promptKeyMap.get(promptKey);
		} else {
			return "";
		}
	}

	public String getPromptContent() {
		return promptContent;
	}

	public void setPromptContent(String promptContent) {
		this.promptContent = promptContent;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getCreateID() {
		return createID;
	}

	public void setCreateID(Integer createID) {
		this.createID = createID;
	}

	public Integer getGuideLanguageID() {
		return guideLanguageID;
	}

	public void setGuideLanguageID(Integer guideLanguageID) {
		this.guideLanguageID = guideLanguageID;
	}

}

src/com/cdel/advc/major/domain/Major.java
package com.cdel.advc.major.domain;

import java.util.Date;

import com.cdel.util.Contants;
import com.cdel.util.DateUtil;
import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * QzMajor entity.
 * 
 * @author zhangsulei
 */

public class Major extends BaseDomain implements java.io.Serializable {
	private static final long serialVersionUID = 7193900830270819888L;
	private Integer majorID;
	private String majorName;
	private Integer businessID;
	private Integer siteID;
	private String siteName;
	private String shortName;// 简称
	private Short status;
	private Integer sequence;
	private Integer creator;
	private Date createTime;
	private String businessName;
	private String creatorName;// 创建者名字
	private Short reportDateSpace;// 学习报告生成间隔时间
	private Short isNewService;// 是否开启短信发送
	private String planSmsTemplate;// 短信模板
	private Date examDate;// 考试日期
	private Short roomStatus;// 聊天室
	private Short enterRoom;// 是否可以进入聊天室
	private Short reportStatus;// 是否开启学习报告
	private Date reportDate;// 报告生成时间

	public Integer getMajorID() {
		return majorID;
	}

	public void setMajorID(Integer majorID) {
		this.majorID = majorID;
	}

	public String getMajorName() {
		return majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	public Integer getBusinessID() {
		return businessID;
	}

	public void setBusinessID(Integer businessID) {
		this.businessID = businessID;
	}

	public Integer getSiteID() {
		return siteID;
	}

	public void setSiteID(Integer siteID) {
		this.siteID = siteID;
	}

	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public String getStatusStr() {
		if (status == null) {
			return "";
		} else {
			return Contants.status.get(status);
		}
	}

	public Integer getSequence() {
		return sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	public Integer getCreator() {
		return creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateTimeStr() {
		return DateUtil.getNowDateString(getCreateTime(), "yyyy-MM-dd HH:mm");
	}

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getCreatorName() {
		return creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	public Short getReportDateSpace() {
		return reportDateSpace;
	}

	public void setReportDateSpace(Short reportDateSpace) {
		this.reportDateSpace = reportDateSpace;
	}

	public String getSiteName() {
		return siteName;
	}

	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	public Short getIsNewService() {
		return isNewService;
	}

	public void setIsNewService(Short isNewService) {
		this.isNewService = isNewService;
	}

	public String getPlanSmsTemplate() {
		return planSmsTemplate;
	}

	public void setPlanSmsTemplate(String planSmsTemplate) {
		this.planSmsTemplate = planSmsTemplate;
	}

	public Date getExamDate() {
		return examDate;
	}

	public void setExamDate(Date examDate) {
		this.examDate = examDate;
	}

	public Short getRoomStatus() {
		return roomStatus;
	}

	public void setRoomStatus(Short roomStatus) {
		this.roomStatus = roomStatus;
	}

	public Short getEnterRoom() {
		return enterRoom;
	}

	public void setEnterRoom(Short enterRoom) {
		this.enterRoom = enterRoom;
	}

	public Short getReportStatus() {
		return reportStatus;
	}

	public void setReportStatus(Short reportStatus) {
		this.reportStatus = reportStatus;
	}

	public Date getReportDate() {
		return reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public String getReportDateStr() {
		return DateUtil.getNowDateString(getReportDate(), "yyyy-MM-dd");
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((majorID == null) ? 0 : majorID.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Major))
			return false;
		Major other = (Major) obj;
		if (majorID == null) {
			if (other.majorID != null)
				return false;
		} else if (!majorID.equals(other.majorID))
			return false;
		return true;
	}

}

src/com/cdel/advc/major/domain/SpecialGeneral.java
package com.cdel.advc.major.domain;

import java.util.Date;

import com.cdel.util.DateUtil;
import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * 特殊日期设置
 * 
 * @author zhangsulei
 */

public class SpecialGeneral extends BaseDomain implements java.io.Serializable {
	private static final long serialVersionUID = 7193900830270819888L;

	private Integer specialGeneralID;
	private Integer majorID;
	private String majorName;
	private Date generalDay;// 日期
	private Integer longTime;// 时间(秒)
	private Integer LongTimeMin;// 时间(分钟)
	private String createName;// 添加人
	private Date createTime;
	private Integer creator;// 添加人

	public Integer getSpecialGeneralID() {
		return specialGeneralID;
	}

	public void setSpecialGeneralID(Integer specialGeneralID) {
		this.specialGeneralID = specialGeneralID;
	}

	public Integer getMajorID() {
		return majorID;
	}

	public void setMajorID(Integer majorID) {
		this.majorID = majorID;
	}

	public String getMajorName() {
		return majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	public Date getGeneralDay() {
		return generalDay;
	}

	public void setGeneralDay(Date generalDay) {
		this.generalDay = generalDay;
	}

	public String getGeneralDayStr() {
		return DateUtil.getNowDateString(getGeneralDay(), "yyyy-MM-dd");
	}

	public Integer getLongTime() {
		return longTime;
	}

	public void setLongTime(Integer longTime) {
		this.longTime = longTime;
	}

	public Integer getLongTimeMin() {
		return LongTimeMin;
	}

	public void setLongTimeMin(Integer longTimeMin) {
		LongTimeMin = longTimeMin;
	}

	public String getCreateName() {
		return createName;
	}

	public void setCreateName(String createName) {
		this.createName = createName;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateTimeStr() {
		return DateUtil.getNowDateString(getCreateTime(), "yyyy-MM-dd");
	}

	public Integer getCreator() {
		return creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

}

src/com/cdel/advc/major/action/ClassNoAction.java
package com.cdel.advc.major.action;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import com.cdel.advc.major.domain.ClassNo;
import com.cdel.advc.major.domain.Major;
import com.cdel.advc.major.facade.ClassNoFacade;
import com.cdel.util.BaseAction;
import com.cdel.util.CheckUtil;

/**
 * 辅导的当前班级数
 * 
 * @author 张苏磊
 * 
 */
@SuppressWarnings("serial")
@ManagedBean
@ViewScoped
public class ClassNoAction extends BaseAction<Major> implements Serializable {
	@ManagedProperty(value = "#{classNoFacade}")
	private ClassNoFacade classNoFacade;

	private List<ClassNo> classNoList;// 当前班级数
	private Integer majorID;// 当前辅导ID

	/**
	 * 打开设置班级页面
	 */
	public void showClassNo(Integer majorID) {
		this.majorID = majorID;
		Map<Short, ClassNo> tmpMap = classNoFacade.getClassNoByMajor(majorID);
		classNoList = new ArrayList<ClassNo>();
		ClassNo classNo = null;
		for (int i = 1; i <= 3; i++) {
			classNo = new ClassNo();
			Short key = new Short(i + "");
			classNo.setClassType(key);
			if (i == 1) {
				classNo.setClassTypeName("实验班");
			} else if (i == 2) {
				classNo.setClassTypeName("精品班");
			} else {
				classNo.setClassTypeName("混合班");
			}
			if (tmpMap != null && tmpMap.get(key) != null) {
				classNo.setCurrClassNo(tmpMap.get(key).getCurrClassNo());
			} else {
				classNo.setCurrClassNo(new Short("0"));
			}
			classNoList.add(classNo);
		}
	}

	/**
	 * 修改updateClassNo
	 */
	public void updateClassNo(int index, int majorID) {
		ClassNo classNo = classNoList.get(index);
		Short currClassNo = classNo.getCurrClassNo();
		if (currClassNo == null
				|| !CheckUtil.checkInt(currClassNo.toString(), 3)) {
			this.addWarnMessage("info", "数字不能为空，且长度不能超过3个字符！");
			return;
		}
		try {
			classNo.setMajorID(majorID);
			classNoFacade.updateClassNo(classNo);
			this.addInfoMessage("info", SUCESSINFO);
		} catch (Exception e) {
			e.printStackTrace();
			this.addErrorMessage("info", FAILINFO);
		}
	}

	public void setClassNoFacade(ClassNoFacade classNoFacade) {
		this.classNoFacade = classNoFacade;
	}

	public List<ClassNo> getClassNoList() {
		return classNoList;
	}

	public void setClassNoList(List<ClassNo> classNoList) {
		this.classNoList = classNoList;
	}

	public Integer getMajorID() {
		return majorID;
	}

	public void setMajorID(Integer majorID) {
		this.majorID = majorID;
	}

}

src/com/cdel/advc/major/action/GuideLangueAction.java
package com.cdel.advc.major.action;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.primefaces.model.LazyDataModel;
import com.cdel.advc.major.domain.GuideLanguage;
import com.cdel.advc.major.domain.Major;
import com.cdel.advc.major.facade.GuideLanguageFacade;
import com.cdel.util.BaseAction;

/**
 * 服务项引导语设置action
 * 
 * @author xxg
 * 
 */
@SuppressWarnings("serial")
@ManagedBean
@ViewScoped
public class GuideLangueAction extends BaseAction<Major> implements
		Serializable {

	@ManagedProperty(value = "#{guideLanguageFacade}")
	private GuideLanguageFacade guideLanguageFacade;

	private LazyDataModel<GuideLanguage> guideLanguagePage;
	private GuideLanguage searchGuideLanguage = new GuideLanguage();// 搜索的服务项引导语
	private Integer majorID; // 辅导ID

	@PostConstruct
	public void initGuideLanguageAction() {
		majorID = this.getIntegerParameter("majorID");
		searchGuideLanguage.setMajorID(majorID);
		guideLanguagePage = guideLanguageFacade.findPage(searchGuideLanguage);
		super.heighti = super.calHeight(14f / 20);
	}

	/**
	 * 查询，需要回第一页
	 */
	public void search() {
		pageTable.setFirst(0);
		search4U();
	}

	/**
	 * 查询，不需要回到第一页
	 */
	public void search4U() {
		guideLanguagePage = guideLanguageFacade.findPage(searchGuideLanguage);
		this.updateComponent("searchForm:guideLangueList");
	}

	public void setGuideLanguageFacade(GuideLanguageFacade guideLanguageFacade) {
		this.guideLanguageFacade = guideLanguageFacade;
	}

	public LazyDataModel<GuideLanguage> getGuideLanguagePage() {
		return guideLanguagePage;
	}

	public void setGuideLanguagePage(
			LazyDataModel<GuideLanguage> guideLanguagePage) {
		this.guideLanguagePage = guideLanguagePage;
	}

	public GuideLanguage getSearchGuideLanguage() {
		return searchGuideLanguage;
	}

	public void setSearchGuideLanguage(GuideLanguage searchGuideLanguage) {
		this.searchGuideLanguage = searchGuideLanguage;
	}

	public Integer getMajorID() {
		return majorID;
	}

}

src/com/cdel/advc/major/action/MainMajorAction.java
package com.cdel.advc.major.action;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;

import com.cdel.advc.major.domain.MainMajor;
import com.cdel.advc.major.domain.Major;
import com.cdel.advc.major.facade.MainMajorFacade;
import com.cdel.util.BaseAction;

/**
 * 
 * <p>主库辅导Action</p>
 * 
 * @author Du Haiying
 * Create at:2014-3-12 下午3:14:24
 */
@SuppressWarnings("serial")
@ManagedBean
@SessionScoped
public class MainMajorAction extends BaseAction<Major> implements Serializable {

	@ManagedProperty(value = "#{mainMajorFacade}")
	private MainMajorFacade mainMajorFacade;

	private Integer siteID;// 网站ID
	
	private List<MainMajor> mainMajors;

	@PostConstruct
	public void initMajorAction() {
		siteID = this.getCurrentSiteID();
		this.mainMajors = this.mainMajorFacade.findMajorsBySiteID(siteID);
	}

	public List<MainMajor> getMainMajors() {
		return mainMajors;
	}

	public void setMainMajorFacade(MainMajorFacade mainMajorFacade) {
		this.mainMajorFacade = mainMajorFacade;
	}
}

WebRoot/page/major/guideLanguageList.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>实验班后台管理系统</title>
	<h:outputStylesheet name="page-css.css" library="css"/>
	<h:outputScript name="page.js" library="js"/>
	<script>
	// 根据不同的时间点 隐藏 不同的时间 
	function hiddTime(){
		var uPromptKey= aa.getSelectedValue();
		jQuery("#addForm\\:starttime").html("开始时间");
		jQuery("#addForm\\:endTime").html("结束时间");
		starttime2.enable();
		endTime2.enable();
	    if(uPromptKey ==1 || uPromptKey ==2 || uPromptKey ==3 ){
	    	jQuery("#addForm\\:starttime").html("开始时间<span>（无需输入）</span>");
			jQuery("#addForm\\:starttime span").css("color","red").css("font-size","12px");
			starttime2.disable();
			jQuery("#addForm\\:endTime").html("结束时间<span>（无需输入）</span>");
			jQuery("#addForm\\:endTime span").css("color","red").css("font-size","12px");
			endTime2.disable();
    	}else if(uPromptKey==4){
			jQuery("#addForm\\:starttime").html("开始时间<span>（无需输入）</span>");
			jQuery("#addForm\\:starttime span").css("color","red").css("font-size","12px");
			starttime2.disable();
		}else if(uPromptKey==5){
			jQuery("#addForm\\:endTime").html("结束时间<span>（无需输入）</span>");
			jQuery("#addForm\\:endTime span").css("color","red").css("font-size","12px");
			endTime2.disable();
		}else if(uPromptKey==6){
			jQuery("#addForm\\:starttime").html("开始时间");
			jQuery("#addForm\\:endTime").html("结束时间");
			starttime2.enable();
			endTime2.enable();
		}
	}
	</script>
</h:head>
<h:body>
	<p:growl for="info" id="info" life="3000" />
	<h:form id="searchForm">
	<p:remoteCommand name="selectMajorStageByMajor" actionListener="#{majorStageOther.selectMajorStageByMajor2(guideLangueAction.majorID)}" update="sPhaseNo" autoRun="true"/>
	<p:panel id="dataTablePanel">
		<p:fieldset legend="查询条件" toggleable="true" collapsed="true" widgetVar="searchFieldSet">
		<p:panelGrid columns="4" style="width:100%; text-align:left;">
			<h:outputLabel for="sPhaseNo" value="阶段名称" />
			 <p:selectOneMenu id="sPhaseNo" value="#{guideLangueAction.searchGuideLanguage.stageID}" style="width:200px;" panelStyleClass="minLength" >
				<f:selectItem itemLabel="--请选择--" itemValue="" />
				<f:selectItems value="#{majorStageOther.majorStageList}" var="majorStage" itemLabel="#{majorStage.stageName}" itemValue="#{majorStage.stageID}"/>
			</p:selectOneMenu>
			
			<h:outputLabel for="sStatus" value="状态" />
			<p:selectOneMenu id="sStatus" value="#{guideLangueAction.searchGuideLanguage.status}" style="width:200px;" panelStyleClass="minLength">
				<f:selectItem itemLabel="--请选择--" itemValue="" />
				<f:selectItems value="#{guideLangueReqAction.status.entrySet()}" var="status" itemLabel="#{status.value}" itemValue="#{status.key}"/>
			</p:selectOneMenu>
			
			<p:outputLabel/>
			<p:outputLabel/>
			
			<f:facet name="footer">
				<h:panelGroup style="display:block; text-align:center">
					<p:commandButton id="searchBtn" value="查询" oncomplete="searchFieldSet.toggle();" actionListener="#{guideLangueAction.search}" rendered="#{guideLangueAction.viewAuth}"/>
					<p:spacer width="10px"/>
					<p:commandButton type="reset" value="重置" />
				</h:panelGroup>
			</f:facet>	
		</p:panelGrid>
		</p:fieldset>
		
		<p:menubar>
			<p:menuitem value="添加" icon="ui-icon-contact" oncomplete="addDialog.show();" 
				rendered="#{guideLangueReqAction.optAuth}" update=":addForm:addDialog" />
		</p:menubar>
		
		<p:dataTable scrollable="true" scrollHeight="#{guideLangueAction.heighti}" 
			widgetVar="guideLangueTable"
			id="guideLangueList"
			binding="#{guideLangueAction.pageTable}"
			lazy="true"
			value="#{guideLangueAction.guideLanguagePage}" 
			rows="20"
			var="guideLangue" 
			paginator="true" 
			paginatorPosition="bottom"
			currentPageReportTemplate="{currentPage} of {totalPages} 共 {totalRecords}条记录"
			paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="20,50"
			rowIndexVar="row"
			styleClass="gridTable" 
			emptyMessage="对不起，没有查询到数据！"
			rendered="#{guideLangueAction.viewAuth}"
			>
			 
			<p:column headerText="辅导ID" width="8%">
				<h:outputText value="#{guideLangue.majorID}" />
			</p:column>
			<p:column headerText="阶段名称" width="12%">
				<h:outputText value="#{guideLangue.stageName}" title="#{guideLangue.stageName}"/>
			</p:column>
			<p:column headerText="服务项名称" width="12%">
				<h:outputText value="#{guideLangue.serviceName}" />
			</p:column>
			<p:column headerText="提示类型" width="12%">
				<h:outputText value="#{guideLangue.promptName}" title="#{guideLangue.promptName}"/>
			</p:column>
			<p:column headerText="提示内容" width="32%">
				<h:outputText value="#{guideLangue.promptContent}" title="#{guideLangue.promptContent}"/>
			</p:column>
			
			<p:column headerText="创建时间" width="12%">
				<h:outputText value="#{guideLangue.createTimeStr}" />
			</p:column>
			
			<p:column headerText="操作" width="12%">
				 <h:panelGroup style="display:block;">
					<p:commandLink value="#{guideLangue.statusStr}" update=":searchForm:guideLangueList :info" actionListener="#{guideLangueReqAction.changeStatus(guideLangue.guideLanguageID,guideLangue.stageID,guideLangue.serviceID,guideLangue.promptKey,guideLangue.status)}" rendered="#{guideLangueAction.optAuth}"/>
					<h:outputText value="#{guideLangue.statusStr}" rendered="#{!guideLangueAction.optAuth}"/>
					<p:spacer width="5px"/>
					<p:commandLink value="修改" oncomplete="loadDialog.show();" actionListener="#{guideLangueReqAction.update(guideLangue.guideLanguageID)}" update=":loadForm:loadDialog" rendered="#{guideLangueAction.optAuth}"/>
					<p:spacer width="5px"/>
					<p:commandLink value="删除" onstart="return confirmDel();" update="guideLangueList :info" actionListener="#{guideLangueReqAction.delete(guideLangue.guideLanguageID)}"  rendered="#{guideLangueAction.optAuth}"/>
				 </h:panelGroup>
			</p:column>
		</p:dataTable>
		<ui:include src="/page/common/blockUI.xhtml">
			<ui:param name="tableID" value="guideLangueList" />
		</ui:include>
	</p:panel>
	</h:form>
	
	<!-- 添加 页面 -->
	<h:form id="addForm" >
		<p:dialog id="addDialog" header="添加" widgetVar="addDialog" resizable="false" showEffect="fade" hideEffect="fade">
			<ui:include src="load/guideLanguageAdd.xhtml"/>
		</p:dialog>
	</h:form>
	<!-- 修改页面 -->
	<h:form id="loadForm" >
		<p:dialog id="loadDialog" header="修改" widgetVar="loadDialog" resizable="false" showEffect="fade" hideEffect="fade">
			   <ui:include src="load/guideLanguageUpdate.xhtml"/>   
		</p:dialog>
	</h:form>
	 
</h:body>
</html>