src/com/cdel/advc/plan/domain/MemberChapterSet.java
package com.cdel.advc.plan.domain;

import java.io.Serializable;
import com.cdel.util.CodeUtil;
import com.cdel.util.Contants;
import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * <p>
 * 计划项学习要求设置 实体
 * </p>
 * 
 * @author Du Haiying Create at:2013-8-15 下午2:36:27
 */
@SuppressWarnings("serial")
public class MemberChapterSet extends BaseDomain implements Serializable {

	private Integer chapterSetID;

	private Integer chapterID;

	private Integer userID;

	/** 建议时间 */
	private Short suggestStyTime;

	/** 学员建议 */
	private String studyAsk;

	/** 是否预习计划章节标识 */
	private Short preChapter;

	/** 学习计划章节正在学习或已停止学习标识 */
	private Short isStudy;

	// -------------- vo dto ------------------------//
	/** 学习提示 */
	private String studyAsk1;

	/** 学习建议 */
	private String studyAsk2;

	/** 完成标准 */
	private String studyAsk3;

	/** 备注 */
	private String studyAsk4;

	/** 建议时间小时属性值 */
	private Double suggestStyTimeHour;

	// --------------- dto------------//
	/** 主计划ID */
	private Integer planID;
	private Short type;
	private String chapterName;
	private Integer creator;
	private String creatorName;
	private Integer sequence;
	private String courseName;
	private Short phaseNo;
	private Short openStatus;
	private Integer planChpID;
	private String courseIDs;

	public Double getSuggestStyTimeHour() {
		return suggestStyTimeHour;
	}

	public void setSuggestStyTimeHour(Double suggestStyTimeHour) {
		this.suggestStyTimeHour = suggestStyTimeHour;
		this.suggestStyTime = (short) (60 * this.suggestStyTimeHour);
	}

	public Integer getCreator() {
		return creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public String getCreatorName() {
		return creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	public String getChapterName() {
		return chapterName;
	}

	public void setChapterName(String chapterName) {
		this.chapterName = chapterName;
	}

	public Short getType() {
		return type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public String getStudyAsk1() {
		return studyAsk1;
	}

	public void setStudyAsk1(String studyAsk1) {
		this.studyAsk1 = studyAsk1;
	}

	public String getStudyAsk2() {
		return studyAsk2;
	}

	public void setStudyAsk2(String studyAsk2) {
		this.studyAsk2 = studyAsk2;
	}

	public String getStudyAsk3() {
		return studyAsk3;
	}

	public void setStudyAsk3(String studyAsk3) {
		this.studyAsk3 = studyAsk3;
	}

	public String getStudyAsk4() {
		return studyAsk4;
	}

	public void setStudyAsk4(String studyAsk4) {
		this.studyAsk4 = studyAsk4;
	}

	public Short getSuggestStyTime() {
		return suggestStyTime;
	}

	public void setSuggestStyTime(Short suggestStyTime) {
		this.suggestStyTime = suggestStyTime;
		this.suggestStyTimeHour = CodeUtil
				.minute2HourNumber(this.suggestStyTime);
	}

	public Integer getChapterSetID() {
		return chapterSetID;
	}

	public void setChapterSetID(Integer chapterSetID) {
		this.chapterSetID = chapterSetID;
	}

	public Integer getUserID() {
		return userID;
	}

	public void setUserID(Integer userID) {
		this.userID = userID;
	}

	public String getStudyAsk() {
		return studyAsk;
	}

	public void setStudyAsk(String studyAsk) {
		this.studyAsk = studyAsk;
	}

	public Integer getChapterID() {
		return chapterID;
	}

	public void setChapterID(Integer chapterID) {
		this.chapterID = chapterID;
	}

	public Short getPreChapter() {
		return preChapter;
	}

	public void setPreChapter(Short preChapter) {
		this.preChapter = preChapter;
	}

	public Short getIsStudy() {
		return isStudy;
	}

	public void setIsStudy(Short isStudy) {
		this.isStudy = isStudy;
	}

	public Integer getPlanID() {
		return planID;
	}

	public void setPlanID(Integer planID) {
		this.planID = planID;
	}

	public Integer getSequence() {
		return sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public Short getPhaseNo() {
		return phaseNo;
	}

	public void setPhaseNo(Short phaseNo) {
		this.phaseNo = phaseNo;
	}

	public Short getOpenStatus() {
		return openStatus;
	}

	public void setOpenStatus(Short openStatus) {
		this.openStatus = openStatus;
	}

	public String getIsStudyStr() {
		if (this.isStudy == null || this.isStudy == 1) {
			return "在学习";
		} else {
			return "已删除";
		}
	}

	/** 开通状态显示值 */
	public String getOpenStatusStr() {
		if (this.openStatus == null) {
			return "";
		}
		return Contants.planChapterOpenStatus.get(this.openStatus);
	}

	public Integer getPlanChpID() {
		return planChpID;
	}

	public void setPlanChpID(Integer planChpID) {
		this.planChpID = planChpID;
	}

	public String getCourseIDs() {
		return courseIDs;
	}

	public void setCourseIDs(String courseIDs) {
		this.courseIDs = courseIDs;
	}

}

src/com/cdel/advc/gdb/plan/action/GdbStudyPlanAction.java
package com.cdel.advc.gdb.plan.action;

import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.primefaces.model.LazyDataModel;
import com.cdel.advc.gdb.plan.domain.GdbStudyPlan;
import com.cdel.advc.gdb.plan.facade.GdbStudyPlanFacade;
import com.cdel.util.BaseAction;

@SuppressWarnings("serial")
@ManagedBean
@ViewScoped
public class GdbStudyPlanAction extends BaseAction<GdbStudyPlan> implements
		Serializable {
	@ManagedProperty("#{gdbStudyPlanFacade}")
	private GdbStudyPlanFacade gdbStudyPlanFacade;

	/** DataTable组件分页模型 */
	private LazyDataModel<GdbStudyPlan> page;
	/** 查询条件 */
	private GdbStudyPlan filterGdbPlan = new GdbStudyPlan();
	private String siteCourseIDs;
	private Integer userID;

	@PostConstruct
	public void initMyAdvanceMemberAction() {
		userID = this.getIntegerParameter("userID");
		siteCourseIDs = this.getParameter("siteCourseIds");
		filterGdbPlan.setUserID(userID);
		super.heighti2 = super.calHeight(14.5f / 20);
		page = gdbStudyPlanFacade.findPage(filterGdbPlan);
	}

	public void search() {
		pageTable.setFirst(0);
		search4U();
	}

	public void search4U() {
		page = gdbStudyPlanFacade.findPage(filterGdbPlan);
		this.updateComponent("searchForm:studyPlanTable");
	}

	public LazyDataModel<GdbStudyPlan> getPage() {
		return page;
	}

	public void setPage(LazyDataModel<GdbStudyPlan> page) {
		this.page = page;
	}

	public GdbStudyPlan getFilterGdbPlan() {
		return filterGdbPlan;
	}

	public void setFilterGdbPlan(GdbStudyPlan filterGdbPlan) {
		this.filterGdbPlan = filterGdbPlan;
	}

	public void setGdbStudyPlanFacade(GdbStudyPlanFacade gdbStudyPlanFacade) {
		this.gdbStudyPlanFacade = gdbStudyPlanFacade;
	}

	public String getSiteCourseIDs() {
		return siteCourseIDs;
	}

	public Integer getUserID() {
		return userID;
	}

}

src/com/cdel/advc/gdb/plan/action/GdbStudyPlanReqAction.java
package com.cdel.advc.gdb.plan.action;

import java.io.Serializable;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import com.cdel.advc.gdb.plan.domain.GdbStudyPlan;
import com.cdel.advc.gdb.plan.facade.GdbStudyPlanFacade;
import com.cdel.util.BaseAction;
import com.cdel.util.Contants;
import com.cdel.util.DateUtil;

@SuppressWarnings("serial")
@ManagedBean
public class GdbStudyPlanReqAction extends BaseAction<GdbStudyPlan> implements
		Serializable {

	@ManagedProperty("#{gdbStudyPlanFacade}")
	private GdbStudyPlanFacade gdbStudyPlanFacade;

	private GdbStudyPlan uGdbStudyPlan = new GdbStudyPlan();
	private byte submitSuccess = 0;// 修改是否成功

	/**
	 * 更新状态
	 * 
	 * @throws Exception
	 */
	public void changeStatus(Integer studyPlanID, Short status)
			throws Exception {
		GdbStudyPlan gs = new GdbStudyPlan();
		gs.setStudyPlanID(studyPlanID);
		if (status == 1) {
			gs.setStatus((short) 0);
		} else {
			gs.setStatus((short) 1);
		}
		try {
			this.gdbStudyPlanFacade.update(gs);
			GdbStudyPlanAction ga = (GdbStudyPlanAction) this
					.getViewAction("gdbStudyPlanAction");
			ga.search4U();
			this.addMessage("info", SUCESSINFO);
		} catch (Exception e) {
			e.printStackTrace();
			this.addErrorMessage("info", FAILINFO);
		}
	}

	/**
	 * 打开修改页面
	 * 
	 * @param studyPlanID
	 */
	public void update(Integer studyPlanID) {
		uGdbStudyPlan = gdbStudyPlanFacade.findByID(studyPlanID);
	}

	/**
	 * 打开添加页面
	 * 
	 * @param studyPlanID
	 */
	public void add() {
		uGdbStudyPlan.setStatus((short) 1);
	}

	/**
	 * 提交修改
	 */
	public void updateSubmit(byte flag) {
		try {
			if (gdbStudyPlanFacade.check(flag, uGdbStudyPlan)) {
				GdbStudyPlanAction ga = (GdbStudyPlanAction) this
						.getViewAction("gdbStudyPlanAction");
				if (flag == 0) {
					uGdbStudyPlan.setUserID(ga.getUserID());
					uGdbStudyPlan.setEndDate(DateUtil.getAfterDate(
							uGdbStudyPlan.getStartDate(), 7));
					uGdbStudyPlan.setCreateTime(new Date());
					uGdbStudyPlan.setCreateUserId(this.getCurrentUserID());
					gdbStudyPlanFacade.add(uGdbStudyPlan);
					ga.search();
				} else {
					uGdbStudyPlan.setUpdateTime(new Date());
					gdbStudyPlanFacade.update(uGdbStudyPlan);
					ga.search4U();
				}
				submitSuccess = 1;
			}
		} catch (Exception e) {
			submitSuccess = -1;
			e.printStackTrace();
		}
		this.addCallbackParam("result", submitSuccess);
	}

	public Map<Integer, String> getWeekNum() {
		Map<Integer, String> map = new LinkedHashMap<Integer, String>();
		for (int i = 1; i <= 52; i++) {
			map.put(i, "第" + i + "周");
		}
		return map;
	}

	public Map<Short, String> getStatus() {
		return Contants.status;
	}

	public void setGdbStudyPlanFacade(GdbStudyPlanFacade gdbStudyPlanFacade) {
		this.gdbStudyPlanFacade = gdbStudyPlanFacade;
	}

	public GdbStudyPlan getuGdbStudyPlan() {
		return uGdbStudyPlan;
	}

	public void setuGdbStudyPlan(GdbStudyPlan uGdbStudyPlan) {
		this.uGdbStudyPlan = uGdbStudyPlan;
	}

}

src/com/cdel/advc/plan/action/BatchGenPlanAction.java
/*
 * @Title: BatchGenPlanAction.java
 * @Package com.cdel.advc.plan.action
 * @Description: TODO
 * @author Du Haiying duhaiying1985@chinaacc.com
 * @date 2013-8-21 下午1:53:36
 * @version V1.0
 *
 * Modification History:  
 * Date         Author      Version     Description  
 * -------------------------------------------------------------- 
 * 2013-8-21                          
 */
package com.cdel.advc.plan.action;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import com.cdel.advc.plan.domain.BatchGenPlan;
import com.cdel.util.BaseAction;

/**
 * <p>
 * 批量生成辅导下班级学员计划 bean
 * </p>
 * 
 * @author Du Haiying Create at:2013-8-21 下午1:53:36
 */
@ManagedBean
@SuppressWarnings("serial")
@ViewScoped
public class BatchGenPlanAction extends BaseAction<BatchGenPlan> {

	private Integer majorID;
	private Short planType;
	private Integer siteID;// 网站ID

	@PostConstruct
	public void initTechnologyMsgAction() {
		siteID = this.getCurrentSiteID();
		super.heighti2 = super.calHeight(12f / 20);
	}

	public void checkGenPlans(byte flag) {

		if (this.majorID == null) {
			this.addWarnMessage("info", "请选择辅导！");
			return;
		}
		if (this.planType == null) {
			this.addWarnMessage("info", "请选择计划类型！");
			return;
		}
		if (flag == 0) {
			this.updateComponent("searchForm:messagesTable");
			this.executeScript("cd.show()");
		} else {
			this.executeScript("cd1.show()");
		}
	}

	/** “删除计划、后门” */
	public boolean isCanDelete() {
		return 1242 == this.getCurrentUserID()
				|| 634 == this.getCurrentUserID();
	}

	public Integer getMajorID() {
		return majorID;
	}

	public void setMajorID(Integer majorID) {
		this.majorID = majorID;
	}

	public Short getPlanType() {
		return planType;
	}

	public void setPlanType(Short planType) {
		this.planType = planType;
	}

	public Integer getSiteID() {
		return siteID;
	}

}

src/com/cdel/advc/plan/action/BatchGenPlanReqAction.java
/*
 * @Title: BatchGenPlanAction.java
 * @Package com.cdel.advc.plan.action
 * @Description: TODO
 * @author Du Haiying duhaiying1985@chinaacc.com
 * @date 2013-8-21 下午1:53:36
 * @version V1.0
 *
 * Modification History:  
 * Date         Author      Version     Description  
 * -------------------------------------------------------------- 
 * 2013-8-21                          
 */
package com.cdel.advc.plan.action;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;

import com.cdel.advc.classes.domain.Classes;
import com.cdel.advc.classes.facade.ClassesFacade;
import com.cdel.advc.memberclass.domain.MemberClass;
import com.cdel.advc.memberclass.facade.MemberClassFacade;
import com.cdel.advc.plan.domain.BatchGenPlan;
import com.cdel.advc.plan.domain.StudyPlan;
import com.cdel.advc.plan.facade.StudyPlanFacade;
import com.cdel.util.BaseAction;
import com.cdel.util.Contants;
import com.cdel.util.ExceptionUtil;

/**
 * <p>
 * 批量生成辅导下班级学员计划 bean
 * </p>
 * 
 * @author Du Haiying Create at:2013-8-21 下午1:53:36
 */
@ManagedBean
@SuppressWarnings("serial")
public class BatchGenPlanReqAction extends BaseAction<BatchGenPlan> {

	@ManagedProperty("#{studyPlanFacade}")
	private StudyPlanFacade studyPlanFacade;
	@ManagedProperty("#{memberClassFacade}")
	private MemberClassFacade memberClassFacade;
	@ManagedProperty("#{classesFacade}")
	private ClassesFacade classesFacade;

	private Integer majorID;
	private Short planType;
	private List<String> messages;
	private byte delClassNum;// 删除班级数
	private byte submitSuccess = 0;// 修改是否成功

	/**
	 * 批量生成辅导下的计划
	 * 
	 * @throws Exception
	 */
	public void genPlans() throws Exception {
		BatchGenPlanAction ba = (BatchGenPlanAction) this
				.getViewAction("batchGenPlanAction");
		majorID = ba.getMajorID();
		planType = ba.getPlanType();
		if (majorID == null || planType == null) {
			this.addWarnMessage("info", "非法参数！");
			return;
		}
		// 先查找学员
		MemberClass mc = new MemberClass();
		mc.setMajorID(majorID);
		mc.setClassStatus((short) 1);
		mc.setStatus((short) 1);
		List<MemberClass> memberPlans = memberClassFacade
				.getMemberClassList(mc);
		int count = 0;
		if (memberPlans == null || (count = memberPlans.size()) == 0) {
			this.addInfoMessage("info", "辅导下不存在学员！");
			return;
		}
		this.messages = new ArrayList<String>();
		this.messages.add("<font style='color:red'>共查找到" + count
				+ "个学员，开始生成...</font>");

		StudyPlan sp = new StudyPlan();
		sp.setPlanType(planType);
		sp.setPlanCreatorID(this.getCurrentUserID());
		sp.setPlanCreatorName(this.getCurrentUserName());

		for (MemberClass memberPlan : memberPlans) {
			sp.setClassID(memberPlan.getClassID());
			sp.setUserID(memberPlan.getUserID());
			sp.setCreateTime(memberPlan.getEnterTime());
			sp.setStudyCourse(memberPlan.getStudyCourse());

			try {
				this.studyPlanFacade.addStudyPlan(sp);
				this.messages.add("<font style='color:blue'>学员"
						+ memberPlan.getUserName() + "生成成功！</font>");
			} catch (IllegalArgumentException e) {
				this.messages
						.add("<font style='color:red'>学员<font style='color:blue'>"
								+ memberPlan.getUserName()
								+ "</font>生成计划失败，原因:"
								+ e.getMessage()
								+ "</font>");
			}
		}

		this.messages.add("<font style='color:blue'>操作结束.</font>");

		this.updateComponent("searchForm:messagesTable");
	}

	/**
	 * 删除学习计划
	 */
	@SuppressWarnings({ "rawtypes", "unchecked" })
	public void deletePlans() {
		BatchGenPlanAction ba = (BatchGenPlanAction) this
				.getViewAction("batchGenPlanAction");
		majorID = ba.getMajorID();
		planType = ba.getPlanType();
		if (majorID == null || planType == null) {
			this.addWarnMessage("info", "非法参数！");
			return;
		}
		// 先查找班级
		try {
			HashMap map = new HashMap();
			map.put("majorID", majorID);
			map.put("num", delClassNum);
			List<Classes> classesList = classesFacade
					.getClassesListByMajorID2(map);
			for (Classes classes : classesList) {
				HashMap paramMap = new HashMap();
				paramMap.put("classID", classes.getClassID());
				paramMap.put("planType", planType);
				studyPlanFacade.removeStudyPlan(paramMap);
			}
			submitSuccess = 1;
		} catch (Exception e) {
			e.printStackTrace();
			logger.error("删除学习计划");
			logger.error(ExceptionUtil.getEMsg(e));
			submitSuccess = -1;
		}
		this.addCallbackParam("result", submitSuccess);
	}

	/**
	 * 学习计划类型
	 */
	public Map<Short, String> getPlanTypes() {
		return Contants.planType;
	}

	public void setStudyPlanFacade(StudyPlanFacade studyPlanFacade) {
		this.studyPlanFacade = studyPlanFacade;
	}

	public List<String> getMessages() {
		return messages;
	}

	public void setMemberClassFacade(MemberClassFacade memberClassFacade) {
		this.memberClassFacade = memberClassFacade;
	}

	public byte getDelClassNum() {
		return delClassNum;
	}

	public void setDelClassNum(byte delClassNum) {
		this.delClassNum = delClassNum;
	}

	public void setClassesFacade(ClassesFacade classesFacade) {
		this.classesFacade = classesFacade;
	}

}

WebRoot/page/plan/load/batchDelete.xhtml
<h:form xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"  
	id="deleteForm">
<p:dialog header="#{memberChapterSetAction.flag == 0?'已停止学习的计划':'正在学习的计划'}" id="deleteDialog" widgetVar="deleteDialog" 
	resizable="false" showEffect="fade" hideEffect="fade" height="500" width="700">
	<p:dataTable value="#{memberChapterSetAction.planChapters}" 
		var="c" 
		emptyMessage="对不起，没有查询到数据！"
		selection="#{memberChapterSetReqAction.selectedChapters}"
		rowKey="#{c.sequence}">
		<p:column selectionMode="multiple" width="7%"/>
		<p:column headerText="课程" width="43%">
			<h:outputText value="#{c.courseName}"/>
		</p:column>	
		<p:column headerText="章节" width="40%">
			<h:outputText value="#{c.chapterName}"/>
			<span class="chapterOpenStatus-#{c.openStatus}">(阶段 #{c.phaseNo}, #{c.openStatusStr})</span>				
		</p:column>
		<p:column width="10%" headerText="状态">
			<h:outputText value="#{c.isStudyStr}" styleClass="status-#{c.isStudy}"/>
		</p:column>
	</p:dataTable>
	
	<f:facet name="footer">
		<h:panelGroup style="display:block; text-align:center">
			<p:messages id="msg"/>
			<p:commandButton value="#{memberChapterSetAction.flag == 0?'恢复学习':'停止学习'}" oncomplete="optResultAlert(args,#{memberChapterSetAction.flag},'myReload');" 
				actionListener="#{memberChapterSetReqAction.updateStudyStatuss(memberChapterSetAction.flag,memberChapterSetAction.planType,memberChapterSetAction.planID,memberChapterSetAction.userID)}"/>
			<p:commandButton value="关闭" type="button" onclick="deleteDialog.hide();"/>
		</h:panelGroup>
	</f:facet>
</p:dialog>
</h:form>

WebRoot/page/plan/load/batchSort.xhtml
<h:form xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui"  
	id="updateBatchSortForm">
<style>
	.ui-orderlist .ui-orderlist-item {cursor: move;font-weight: inherit;
		font-size: 12px;border: 1px solid #DDDDDD;color: #362B36;}
	.ui-orderlist .ui-orderlist-list li { padding: 5px;}
</style>

<p:dialog header="计划项批量排序" widgetVar="updateBatchSortDialog" id="updateBatchSortDialog"
	resizable="false" showEffect="fade" hideEffect="fade" height="500" width="900">
	<p:orderList id="orderList" converter="planChapterSequenceSetConverter"
		 value="#{planChapterSequenceSetReqAction.sortChapters}" 
		 var="c" itemValue="#{c}" >
	    <f:facet name="caption">
			<h:outputLabel value="课程/学习内容"/>
	    </f:facet>  
		<p:column style="width:10%;">
			<h:outputText value="排序#{c.sequence}"/>
		</p:column>	
		<p:column style="width:50%;">
			<h:outputText  value="#{c.courseName}"/>
		</p:column>	
		<p:column style="width:40%;">
			#{c.chapterName}
			<span class="chapterOpenStatus-#{c.openStatus}">(阶段 #{c.phaseNo}, #{c.openStatusStr})</span>				
		</p:column>	
	</p:orderList>

	<f:facet name="footer">
		<h:panelGroup style="display:block; text-align:center">
			<h:inputHidden value="#{planChapterSequenceSetReqAction.planID}"/>
			<p:commandButton value="保存" type="button" onclick="cd3.show()"/>
			<p:commandButton value="关闭" type="button" onclick="updateBatchSortDialog.hide();"/>
		</h:panelGroup>
	</f:facet>
</p:dialog>

<p:confirmDialog widgetVar="cd3" severity="alert" message="确定要重新排序，同时重新生成学习计划?" header="信息提示">
	<p:commandButton value="确定" 
		onstart="cd3.hide()" update=":info"
		oncomplete="optResultAlert(args,9,'myReload');"
		actionListener="#{planChapterSequenceSetReqAction.updateChapterSequences(planChapterSequenceSetReqAction.planID)}" />
	<p:commandButton value="取消" onclick="cd3.hide();" type="button" />
</p:confirmDialog>
</h:form>

WebRoot/page/plan/load/showLog.xhtml
<h:form id="logForm" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui" >
	<p:dialog header="修改日志" widgetVar="logDialog" id="logDialog" resizable="false" showEffect="fade" hideEffect="fade"  dynamic="false">
		<p:dataTable rendered="#{!empty planChapterAction.plan}"
			id="logList" 
			value="#{planLogAction.logPage}" var="log" 
			lazy="true"	rows="20" paginator="true" paginatorPosition="bottom"
			currentPageReportTemplate="{currentPage} of {totalPages} 共 {totalRecords}条记录"
			paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="20,50"	styleClass="gridTable" 	emptyMessage="对不起，没有查询到数据！">
			<p:column headerText="日志信息">
					<h:outputText value="#{log.planLogDesc}" />
			</p:column>
		</p:dataTable>
	</p:dialog>
</h:form>
