src/com/cdel/advc/course/domain/Course.java
package com.cdel.advc.course.domain;

import java.util.Date;

import com.cdel.util.Contants;
import com.cdel.util.DateUtil;
import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * 课程 entity.
 * 
 * @author Haiying Du
 */

public class Course extends BaseDomain implements java.io.Serializable {

	private static final long serialVersionUID = 4395192876602468963L;
	private Integer courseID;// ID
	private Integer majorID;// 辅导（职称）ID
	private String courseName;// 课程名称
	private Short courseType;// 课程类型：实验班1、精品班2
	private String courseCode;// 课程代码，来自选课系统
	private Short courseYear;// 课程年份
	private Integer previewCourse;// 预习课程
	private Short status;// 状态：1 正常，2 异常
	private Integer creator;// 创建人
	private Date createTime;// 创建时间
	private String courseSmsName;// 短信课程名
	private Short isMemberMsgOpen;// 是否开通
	private String memberMsgTitle;// 消息标题
	private String memberMsgContent;// 消息内容
	private Integer listID;// 内容答疑板ID(对内课ID)
	private Short isPre;// 是否预习课程标识
	private Integer siteID;// 站点ID
	private Short faceType;// 是否面授课，0：否；1：是

	// ---vo相关属性
	private String majorName;
	private String teacherName;// 创建者老师名字
	private String previewCourseName;
	private String courseTypes;// 课程类型：实验班1、精品班2
	private String courseCodes;
	private String courseSet;// 套餐下对应的 课程集合
	public String getCourseSet() {
		return courseSet;
	}

	public void setCourseSet(String courseSet) {
		this.courseSet = courseSet;
	}

	public Course() {
		super();
	}

	public Integer getCourseID() {
		return courseID;
	}

	public void setCourseID(Integer courseID) {
		this.courseID = courseID;
	}

	public Integer getMajorID() {
		return majorID;
	}

	public void setMajorID(Integer majorID) {
		this.majorID = majorID;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public Short getCourseType() {
		return courseType;
	}

	public void setCourseType(Short courseType) {
		this.courseType = courseType;
	}

	public String getCourseCode() {
		return courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	public Short getCourseYear() {
		return courseYear;
	}

	public void setCourseYear(Short courseYear) {
		this.courseYear = courseYear;
	}

	public Integer getPreviewCourse() {
		return previewCourse;
	}

	public void setPreviewCourse(Integer previewCourse) {
		this.previewCourse = previewCourse;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Integer getCreator() {
		return creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCourseSmsName() {
		return courseSmsName;
	}

	public void setCourseSmsName(String courseSmsName) {
		this.courseSmsName = courseSmsName;
	}

	public Short getIsMemberMsgOpen() {
		return isMemberMsgOpen;
	}

	public void setIsMemberMsgOpen(Short isMemberMsgOpen) {
		this.isMemberMsgOpen = isMemberMsgOpen;
	}

	public String getMemberMsgTitle() {
		return memberMsgTitle;
	}

	public void setMemberMsgTitle(String memberMsgTitle) {
		this.memberMsgTitle = memberMsgTitle;
	}

	public String getMemberMsgContent() {
		return memberMsgContent;
	}

	public void setMemberMsgContent(String memberMsgContent) {
		this.memberMsgContent = memberMsgContent;
	}

	public Integer getListID() {
		return listID;
	}

	public void setListID(Integer listID) {
		this.listID = listID;
	}

	public Short getIsPre() {
		return isPre;
	}

	public void setIsPre(Short isPre) {
		this.isPre = isPre;
	}

	public String getMajorName() {
		return majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	/**
	 * 得到课程类型名称
	 */
	public String getCourseTypeStr() {
		if (this.courseType == null || this.courseType == 0) {
			return "";
		}
		return Contants.courseTypeMap.get(this.courseType);
	}

	public String getPreviewCourseName() {
		return previewCourseName;
	}

	public void setPreviewCourseName(String previewCourseName) {
		this.previewCourseName = previewCourseName;
	}

	/**
	 * 得到课程状态名称
	 */
	public String getStatusStr() {
		if (this.status == null) {
			return "";
		}
		return Contants.status.get(status);
	}

	public String getCreateTimeStr() {
		return DateUtil.getNowDateString(createTime, "yyyy-MM-dd");
	}

	public Integer getSiteID() {
		return siteID;
	}

	public void setSiteID(Integer siteID) {
		this.siteID = siteID;
	}

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public Short getFaceType() {
		return faceType;
	}

	public void setFaceType(Short faceType) {
		this.faceType = faceType;
	}

	public String getFaceTypeStr() {
		if (this.faceType == null) {
			return "";
		}
		return Contants.yesorno.get(faceType);
	}

	public String getCourseTypes() {
		return courseTypes;
	}

	public void setCourseTypes(String courseTypes) {
		this.courseTypes = courseTypes;
	}

	public String getCourseCodes() {
		return courseCodes;
	}

	public void setCourseCodes(String courseCodes) {
		this.courseCodes = courseCodes;
	}

	@Override
	public String toString() {
		return "Course [courseID=" + courseID + ", majorID=" + majorID
				+ ", courseName=" + courseName + ", courseType=" + courseType
				+ ", courseCode=" + courseCode + ", courseYear=" + courseYear
				+ ", previewCourse=" + previewCourse + ", status=" + status
				+ ", creator=" + creator + ", createTime=" + createTime
				+ ", courseSmsName=" + courseSmsName + ", listID=" + listID
				+ ", isPre=" + isPre + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((courseID == null) ? 0 : courseID.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Course))
			return false;
		Course other = (Course) obj;
		if (courseID == null) {
			if (other.courseID != null)
				return false;
		} else if (!courseID.equals(other.courseID))
			return false;
		return true;
	}

}

src/com/cdel/advc/course/domain/StudyAsk.java
package com.cdel.advc.course.domain;

import java.io.Serializable;
import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * Domain Object.学习要求
 * 
 * @version 1.0 2009-4-13
 * @author Arthur Liu - arthurliu@chinaacc.com
 */
@SuppressWarnings("serial")
public class StudyAsk extends BaseDomain implements Serializable {

	private Short suggestStyTime;
	private Short suggestStyTime4Hour;
	private Short type;
	private Integer chapterID;
	private String content;
	private Integer askID;
	private String studyAsk1;
	private String studyAsk2;
	private String studyAsk3;
	private String studyAsk4;

	public void setStudyAsk1(String studyAsk1) {
		this.studyAsk1 = studyAsk1;
	}

	public void setStudyAsk2(String studyAsk2) {
		this.studyAsk2 = studyAsk2;
	}

	public void setStudyAsk3(String studyAsk3) {
		this.studyAsk3 = studyAsk3;
	}

	public void setStudyAsk4(String studyAsk4) {
		this.studyAsk4 = studyAsk4;
	}

	public String getStudyAsk1() {
		return studyAsk1;
	}

	public String getStudyAsk2() {
		return studyAsk2;
	}

	public String getStudyAsk3() {
		return studyAsk3;
	}

	public String getStudyAsk4() {
		return studyAsk4;
	}

	public Short getSuggestStyTime() {
		return suggestStyTime;
	}

	public void setSuggestStyTime(Short suggestStyTime) {
		this.suggestStyTime = suggestStyTime;
	}

	public Short getType() {
		return type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Integer getChapterID() {
		return chapterID;
	}

	public void setChapterID(Integer chapterID) {
		this.chapterID = chapterID;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getAskID() {
		return askID;
	}

	public void setAskID(Integer askID) {
		this.askID = askID;
	}

	public Short getSuggestStyTime4Hour() {
		return suggestStyTime4Hour;
	}

	public Integer getSuggestStyTime4HourList() {
		if (suggestStyTime != null) {
			return suggestStyTime / 60;
		} else {
			return null;
		}
	}

	public void setSuggestStyTime4Hour(Short suggestStyTime4Hour) {
		this.suggestStyTime4Hour = suggestStyTime4Hour;
	}

	public String getTypeStr() {
		if (type == 1) {
			return "一门";
		} else if (type == 2) {
			return "二门";
		} else if (type == 3) {
			return "三门";
		} else if (type == 4) {
			return "四门以上";
		} else {
			return "无法确定";
		}
	}

}

src/com/cdel/advc/course/domain/TempChapter.java
package com.cdel.advc.course.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.cdel.util.Contants;
import com.cdel.util.DateUtil;
import com.chnedu.plat.rad.domain.BaseDomain;

/**
 * @author dell（ 章节 实体）学习计划项
 */
@SuppressWarnings("serial")
public class TempChapter extends BaseDomain implements Serializable {
	private Integer chapterID;// 主键
	private Short phaseNo;// 阶段号
	private String chapterName;// 计划项(章节)名
	private Short openStatus;// 开通状态
	private String noteName;// 短信章节名
	private Date openTime;// 开通时间
	private Date createTime;// 创建时间
	private Integer courseID;// 所属课程ID
	private String courseName;// 所属课程
	private String url;// URL
	private Integer opener;// 开通人
	private String openerName;// 开通人
	private Integer creator;// 创建人
	private String qzChapter;// 题库章节ID
	private Integer sequence;// 排序
	private String studyAsk;
	private String studyAsk1;
	private String studyAsk2;
	private String studyAsk3;
	private String studyAsk4;
	private Short suggestStyTime;// 建议时间
	private String teacherName;
	private Integer askNum;// 学习要求个数
	private List<StudyAsk> studyAskList = new ArrayList<StudyAsk>();// 学习要求
	private String stageName;// 阶段名

	public String getChapterName() {
		return chapterName;
	}

	public void setChapterName(String chapterName) {
		this.chapterName = chapterName;
	}

	public Short getPhaseNo() {
		return phaseNo;
	}

	public void setPhaseNo(Short phaseNo) {
		this.phaseNo = phaseNo;
	}

	public Short getOpenStatus() {
		return openStatus;
	}

	public void setOpenStatus(Short openStatus) {
		this.openStatus = openStatus;
	}

	public String getOpenStatusStr() {
		if (this.openStatus == null) {
			return "";
		}
		return Contants.openStatus.get(openStatus);
	}

	public String getNoteName() {
		return noteName;
	}

	public void setNoteName(String noteName) {
		this.noteName = noteName;
	}

	public Date getOpenTime() {
		return openTime;
	}

	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	public String getOpenTimeStr() {
		return DateUtil.getNowDateString(openTime, "yyyy-MM-dd");
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateTimeStr() {
		return DateUtil.getNowDateString(createTime, "yyyy-MM-dd");
	}

	public Integer getCourseID() {
		return courseID;
	}

	public void setCourseID(Integer courseID) {
		this.courseID = courseID;
	}

	public Integer getChapterID() {
		return chapterID;
	}

	public void setChapterID(Integer chapterID) {
		this.chapterID = chapterID;
	}

	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getOpenerName() {
		return openerName;
	}

	public void setOpenerName(String openerName) {
		this.openerName = openerName;
	}

	public Integer getCreator() {
		return creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	public String getQzChapter() {
		return qzChapter;
	}

	public void setQzChapter(String qzChapter) {
		this.qzChapter = qzChapter;
	}

	public Integer getSequence() {
		return sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}

	public String getStudyAsk() {
		return studyAsk;
	}

	public void setStudyAsk(String studyAsk) {
		this.studyAsk = studyAsk;
	}

	public String getStudyAsk1() {
		return studyAsk1;
	}

	public void setStudyAsk1(String studyAsk1) {
		this.studyAsk1 = studyAsk1;
	}

	public String getStudyAsk2() {
		return studyAsk2;
	}

	public void setStudyAsk2(String studyAsk2) {
		this.studyAsk2 = studyAsk2;
	}

	public String getStudyAsk3() {
		return studyAsk3;
	}

	public void setStudyAsk3(String studyAsk3) {
		this.studyAsk3 = studyAsk3;
	}

	public String getStudyAsk4() {
		return studyAsk4;
	}

	public void setStudyAsk4(String studyAsk4) {
		this.studyAsk4 = studyAsk4;
	}

	public Integer getOpener() {
		return opener;
	}

	public void setOpener(Integer opener) {
		this.opener = opener;
	}

	public Short getSuggestStyTime() {
		return suggestStyTime;
	}

	public void setSuggestStyTime(Short suggestStyTime) {
		this.suggestStyTime = suggestStyTime;
	}

	public String getTeacherName() {
		return teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	public Integer getAskNum() {
		return askNum;
	}

	public void setAskNum(Integer askNum) {
		this.askNum = askNum;
	}

	public List<StudyAsk> getStudyAskList() {
		return studyAskList;
	}

	public void setStudyAskList(List<StudyAsk> studyAskList) {
		this.studyAskList = studyAskList;
	}

	public String getStageName() {
		return stageName;
	}

	public void setStageName(String stageName) {
		this.stageName = stageName;
	}

}

src/com/cdel/advc/course/action/CourseReqAction.java
package com.cdel.advc.course.action;

import java.io.Serializable;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.component.UISelectItems;
import com.cdel.advc.course.domain.Course;
import com.cdel.advc.course.facade.CourseFacade;
import com.cdel.util.BaseAction;
import com.cdel.util.Contants;

/**
 * 
 * 课程Bean
 * 
 * @author Haiying Du
 * 
 */
@SuppressWarnings("serial")
@ManagedBean
public class CourseReqAction extends BaseAction<Course> implements Serializable {
	@ManagedProperty(value = "#{courseFacade}")
	private CourseFacade courseFacade;

	private Course showCourse = new Course();// 课程对象
	private UISelectItems preCourseSelectItems; // 预习课程选项对象
	private byte submitSuccess = 0;// 添加是否成功

	/**
	 * 修改状态
	 */
	public void changeStatus(Integer courseID, String courseCode, Integer status) {
		CourseAction courseAction = (CourseAction) this
				.getViewAction("courseAction");
		showCourse.setCourseID(courseID);
		Short newStatus;
		if (status == 1) {
			newStatus = 0;
		} else {
			newStatus = 1;
		}
		showCourse.setStatus(newStatus);
		if (newStatus == 0) {
			try {
				courseFacade.update(showCourse);
				courseAction.search4U();
			} catch (Exception e) {
				e.printStackTrace();
				this.addErrorMessage("info", FAILINFO);
			}
		} else {
			showCourse.setCourseCode(courseCode);
			if (courseFacade.checkCourse((byte) 3, showCourse,
					courseAction.getSiteID())) {
				try {
					courseFacade.update(showCourse);
					courseAction.search4U();
				} catch (Exception e) {
					e.printStackTrace();
					this.addErrorMessage("info", FAILINFO);
				}
			}
		}
		this.addMessage("info", SUCESSINFO);
	}

	/**
	 * 查看
	 */
	public void show(Integer courseID) {
		showCourse = courseFacade.getCourseByCourseID(courseID);
	}

	/**
	 * 打开预习课程关联页面
	 * 
	 * @param courseID
	 */
	public void updatePre(Integer courseID, Integer majorID) {
		showCourse.setIsPre(new Short("1"));
		showCourse.setMajorID(majorID);
		showCourse.setCourseID(courseID);
		preCourseSelectItems.setValue(courseFacade
				.getCourseListByMajor(showCourse));
		showCourse = courseFacade.findByID(courseID);
	}

	/**
	 * 关联预习课程
	 */
	public void addPreSubmit() {
		try {
			courseFacade.update(showCourse);
			submitSuccess = 1;
			this.updateComponent("searchForm:courseList");
		} catch (Exception e) {
			submitSuccess = -1;
			e.printStackTrace();
		}
		this.addCallbackParam("result", submitSuccess);
	}

	public void setCourseFacade(CourseFacade courseFacade) {
		this.courseFacade = courseFacade;
	}

	public Course getShowCourse() {
		return showCourse;
	}

	public void setShowCourse(Course showCourse) {
		this.showCourse = showCourse;
	}

	public Integer[] getYears() {
		return Contants.years;
	}

	public Map<Short, String> getCourseTypeMap() {
		return Contants.courseTypeMap;
	}

	public Map<Integer, String> getIsPreMap() {
		return Contants.isPreMap;
	}

	public Map<Short, String> getFaceTypeMap() {
		return Contants.yesorno;
	}

	public Map<Short, String> getStatus() {
		return Contants.status;
	}

	public Map<Short, String> getIsMemberMsgOpen() {
		return Contants.yesorno;
	}

	public UISelectItems getPreCourseSelectItems() {
		return preCourseSelectItems;
	}

	public void setPreCourseSelectItems(UISelectItems preCourseSelectItems) {
		this.preCourseSelectItems = preCourseSelectItems;
	}

}

WebRoot/page/course/tempChapterList.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>#{tempChapterAction.courseName}的计划项(章节)</title>
	<h:outputStylesheet name="page-css.css" library="css"/>
	<h:outputScript name="page.js" library="js"/>
	<script>
	function callBack(){
		alert("添加成功，请继续设置学习时长和学习要求！");
		window.open("studyAsk.xhtml?chapterID="+jsonResult.chapterID+"&amp;chapterName="+jsonResult.chapterName);
	}
	
	function selectMajorStageByMajorjs(majorID){
		selectMajorStageByMajor([{name:'majorID', value:majorID}]);
	}
	</script>
</h:head>
<h:body>
	<p:growl for="info" id="info" life="3000" />
	<h:form id="searchForm">
	<p:remoteCommand name="selectMajorStageByMajor" actionListener="#{majorStageOther.selectMajorStageByMajor(tempChapterAction.majorID)}" update="sPhaseNo" autoRun="true"/>
	<p:panel id="dataTablePanel">
		<p:fieldset legend="查询条件" toggleable="true" collapsed="true" widgetVar="searchFieldSet">
		<p:panelGrid columns="6" style="width:100%; text-align:left;">
			<h:outputLabel for="sPhaseNo" value="阶段名" />
			<p:selectOneMenu id="sPhaseNo" value="#{tempChapterAction.searchTempChapter.phaseNo}" style="width:200px;" panelStyleClass="minLength" >
				<f:selectItem itemLabel="--请选择--" itemValue="" />
				<f:selectItems value="#{majorStageOther.majorStageList}" var="majorStage" itemLabel="#{majorStage.stageName}" itemValue="#{majorStage.stageID}"/>
			</p:selectOneMenu>

			<h:outputLabel for="sChapterName" value="计划项(章节)名" />
			<p:inputText id="sChapterName" value="#{tempChapterAction.searchTempChapter.chapterName}" styleClass="minLength"/>
			
			<h:outputLabel for="sOpenStatus" value="开通状态" />
			<p:selectOneMenu id="sOpenStatus" value="#{tempChapterAction.searchTempChapter.openStatus}" style="width:200px;" panelStyleClass="minLength">
				<f:selectItem itemLabel="--请选择--" itemValue="" />
				<f:selectItems value="#{tempChapterReqAction.openStatus.entrySet()}" var="openStatus" itemLabel="#{openStatus.value}" itemValue="#{openStatus.key}"/>
			</p:selectOneMenu>
			
			<f:facet name="footer">
				<h:panelGroup style="display:block; text-align:center">
					<p:commandButton id="searchBtn" value="查询" oncomplete="searchFieldSet.toggle();" actionListener="#{tempChapterAction.search}" rendered="#{tempChapterAction.viewAuth}"/>
					<p:spacer width="10px"/>
					<p:commandButton type="reset" value="重置" />
				</h:panelGroup>
			</f:facet>	
		</p:panelGrid>
		</p:fieldset>
		<p:menubar>
			<p:menuitem value="添加" icon="ui-icon-contact" oncomplete="loadDialog.show();" 
				actionListener="#{tempChapterAction.add}" rendered="#{tempChapterAction.optAuth}" update=":loadForm:loadDialog" />
			<p:menuitem value="批量开通" icon="ui-icon-star" oncomplete="optResultAlert(args,3);" 
				actionListener="#{tempChapterReqAction.changeStatusSubmitBatch}" rendered="#{tempChapterAction.optAuth}" update=":info" />
		</p:menubar>
		<p:dataTable scrollable="true" scrollHeight="#{tempChapterAction.heighti2}" 
			widgetVar="tempChapterTable"
			id="tempChapterList"
			binding="#{tempChapterAction.pageTable}"
			lazy="true"
			value="#{tempChapterAction.tempChapterPage}" 
			rows="20"
			var="tempChapter" 
			paginator="true" 
			paginatorPosition="bottom"
			currentPageReportTemplate="{currentPage} of {totalPages} 共 {totalRecords}条记录"
			paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
			rowsPerPageTemplate="20,50"
			rowIndexVar="row"
			styleClass="gridTable" 
			emptyMessage="对不起，没有查询到数据！"
			rendered="#{tempChapterAction.viewAuth}"
			selection="#{tempChapterReqAction.selTempChapters}"
			rowKey="#{tempChapter.chapterID}"
			editable="true" 
			editMode="cell" 
			>
			<p:ajax event="cellEdit" listener="#{tempChapterReqAction.updateSeqSubmit}" update=":info" />
			<p:column width="5%" selectionMode="multiple" />
			<p:column headerText="阶段名" width="7%">
				<h:outputText value="#{tempChapter.stageName}"/>
			</p:column>
			<p:column headerText="计划项(章节)名" width="20%">
				<h:outputText value="#{tempChapter.chapterName}" title="#{tempChapter.chapterName}"/>
			</p:column>
			<p:column headerText="短信章节名" width="20%">
				<h:outputText value="#{tempChapter.noteName}" title="#{tempChapter.noteName}"/>
			</p:column>
			<p:column headerText="开通状态" width="8%">
				<p:commandLink value="#{tempChapter.openStatusStr}" oncomplete="openStatusDialog.show();" update=":openStatusForm:openStatusDialog" actionListener="#{tempChapterReqAction.changeStatus(tempChapter.chapterID)}" rendered="#{tempChapterReqAction.optAuth and tempChapter.openStatus==0}"/>
				<h:outputText value="#{tempChapter.openStatusStr}" rendered="#{!tempChapterReqAction.optAuth or tempChapter.openStatus!=0}"/>
			</p:column>
			<p:column headerText="开通时间" width="10%">
				<h:outputText value="#{tempChapter.openTimeStr}"/>
			</p:column>
			<p:column headerText="创建时间" width="10%">
				<h:outputText value="#{tempChapter.createTimeStr}"/>
			</p:column>
			<p:column headerText="学习要求" width="9%">
				<h:link value="查看(#{tempChapter.askNum})" outcome="studyAsk" includeViewParams="true" target="_blank">
					<f:param name="chapterID" value="#{tempChapter.chapterID}"/>
					<f:param name="chapterName" value="#{tempChapter.chapterName}"/>
				</h:link>
			</p:column>
			<p:column headerText="操作" width="9%">
				<p:commandLink value="查看" oncomplete="showDialog.show();" actionListener="#{tempChapterReqAction.show(tempChapter.chapterID)}" update=":showForm:showDialog" rendered="#{tempChapterAction.viewAuth}"/>
				<p:spacer width="5px"/>
				<p:commandLink value="修改" oncomplete="loadDialog.show();" actionListener="#{tempChapterAction.update(tempChapter.chapterID)}" update=":loadForm:loadDialog" rendered="#{tempChapterAction.optAuth}"/>
			</p:column>
			<p:column headerText="排序" width="5%">
				<p:cellEditor>
					<f:facet name="output">
						<h:outputText value="#{tempChapter.sequence}" title="单击修改"/>
					</f:facet>
					<f:facet name="input">
						<p:inputText value="#{tempChapter.sequence}" style="width:60%;"/>
					</f:facet>
				</p:cellEditor>
			</p:column>
		</p:dataTable>
		<ui:include src="/page/common/blockUI.xhtml">
			<ui:param name="tableID" value="tempChapterList" />
		</ui:include>
	</p:panel>
	</h:form>
	<!-- 查看页面 -->
	<h:form id="showForm" >
		<p:dialog id="showDialog" header="查看学习计划项" widgetVar="showDialog" resizable="false" showEffect="fade" hideEffect="fade">
			<ui:include src="load/tempChapterShow.xhtml"/>
		</p:dialog>
	</h:form>
	<!-- 添加/修改页面 -->
	<h:form id="loadForm" >
		<p:dialog id="loadDialog" header="#{(tempChapterAction.flag==0)?'添加':'修改'}" widgetVar="loadDialog" resizable="false" showEffect="fade" hideEffect="fade">
			<ui:include src="#{tempChapterAction.url}"/>
		</p:dialog>
	</h:form>
	<!-- 开通状态 -->
	<h:form id="openStatusForm" >
		<p:dialog id="openStatusDialog" header="修改开通状态" widgetVar="openStatusDialog" resizable="false" showEffect="fade" hideEffect="fade">
			<ui:include src="load/tempChapterOpen.xhtml"/>
		</p:dialog>
	</h:form>
</h:body>
</html>